# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_post_like_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_flag',
            field=models.NullBooleanField(default=False),
        ),
    ]
