# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_people'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='people',
            new_name='person',
        ),
    ]
