# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20161224_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='followed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
