# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_person_followed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
